/**
 * Static list of migration SQL files with their contents.
 * Used by both browser PGLite and test infrastructure.
 *
 * AUTO-GENERATED by pnpm codegen. Do not edit manually.
 */
import migration0000 from './0000_audit_logs.sql?raw'

// Migration SQL contents (in order)
export const migrations = [
  migration0000,
] as const
